# Generated by Django 3.0.7 on 2020-06-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmatter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
