# Generated by Django 3.0.7 on 2020-06-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmatter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontmatter',
            name='learning_objectives',
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=500)),
                ('frontmatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmatter.Frontmatter')),
            ],
        ),
    ]
