# Generated by Django 3.0.7 on 2020-06-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontmatter', '0002_auto_20200618_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='title',
        ),
    ]
