# Generated by Django 3.0.7 on 2020-06-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmatter', '0003_auto_20200618_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
