# Generated by Django 3.0.7 on 2020-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200709_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('website/page.html', 'Standard'), ('workshop/workshop-list.html', 'Workshop list'), ('library/all-library-items.html', 'Library items')], default='website/page.html', max_length=100),
        ),
    ]
