# Generated by Django 3.0.7 on 2021-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('uncategorized', 'Uncategorized'), ('reading', 'Reading'), ('project', 'Project'), ('tutorial', 'Tutorial'), ('cheatsheet', 'Cheatsheet'), ('dataset', 'Dataset')], default='uncategorized', max_length=13),
        ),
    ]
