# Generated by Django 3.0.7 on 2021-02-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('title', 'url', 'category')},
        ),
    ]
