# Generated by Django 3.0.7 on 2020-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('template', models.CharField(choices=[('website/page.html', 'Standard'), ('workshop/workshop-list.html', 'Workshop list'), ('library/all-library-items.html', 'Library items')], default='website/page.html', max_length=100)),
                ('is_homepage', models.BooleanField(default=False)),
            ],
        ),
    ]
