# Generated by Django 3.0.7 on 2020-08-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='comment',
        ),
    ]
