# Generated by Django 3.0.7 on 2020-08-07 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_auto_20200807_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
