# Generated by Django 3.0.7 on 2021-03-09 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0001_initial'),
        ('workshop', '0003_frontmatter_datasets'),
        ('feedback', '0002_auto_20210220_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('user', 'lesson', 'workshop', 'comment')},
        ),
    ]
