# Generated by Django 3.0.7 on 2020-08-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
        ('lesson', '0001_initial'),
        ('feedback', '0003_auto_20200807_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.Lesson'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.Workshop'),
        ),
    ]
