# Generated by Django 3.0.7 on 2020-07-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20200708_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
