# Generated by Django 3.0.7 on 2020-07-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_lesson_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
    ]
