# Generated by Django 3.0.7 on 2020-06-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
