# Generated by Django 3.0.7 on 2020-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20200617_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_correct_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
