# Generated by Django 3.0.7 on 2020-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
