# Generated by Django 3.0.7 on 2020-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
