# Generated by Django 3.0.7 on 2021-05-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='software_headers/default.jpg', upload_to='software_headers/')),
                ('what', models.TextField(blank=True)),
                ('why', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('header', models.TextField(blank=True)),
                ('instructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='install.Instructions')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='installation_screenshots')),
                ('alt_text', models.TextField(default='No alt text')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='install.Step')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='instructions',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_instructions', to='install.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='instructions',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_instructions', to='install.Software'),
        ),
    ]
