# Generated by Django 3.1.4 on 2021-01-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='gh_name',
        ),
    ]
