# Generated by Django 3.0.7 on 2020-08-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstallationInstruction',
            new_name='Instruction',
        ),
        migrations.RenameModel(
            old_name='InstallationStep',
            new_name='Step',
        ),
        migrations.RenameField(
            model_name='screenshot',
            old_name='installation_step',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='installation',
            new_name='instruction',
        ),
    ]
