# Generated by Django 3.0.7 on 2021-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructions',
            name='what',
        ),
        migrations.RemoveField(
            model_name='instructions',
            name='why',
        ),
        migrations.AddField(
            model_name='software',
            name='what',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='software',
            name='why',
            field=models.TextField(blank=True),
        ),
    ]
