# Generated by Django 3.0.7 on 2020-09-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0002_auto_20200915_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='image',
            field=models.ImageField(default='software_headers/default.jpg', upload_to='software_headers/'),
        ),
    ]
