# Generated by Django 3.0.7 on 2020-08-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0002_auto_20200810_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='alt_text',
            field=models.TextField(default='No alt text'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='installation_screenshots'),
        ),
        migrations.AlterField(
            model_name='step',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='install.Instruction'),
        ),
    ]
