# Generated by Django 3.0.7 on 2020-08-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0003_auto_20200817_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='what',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='why',
            field=models.TextField(blank=True),
        ),
    ]
