# Generated by Django 3.0.7 on 2020-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0004_auto_20200825_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='software',
            field=models.CharField(max_length=250),
        ),
    ]
