# Generated by Django 3.0.7 on 2020-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0005_auto_20200825_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='header',
            field=models.TextField(blank=True),
        ),
    ]
