# Generated by Django 3.0.7 on 2020-08-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0006_step_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='gh_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
