# Generated by Django 3.0.7 on 2020-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0008_auto_20200825_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='gh_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
