# Generated by Django 3.0.7 on 2021-02-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='label',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
