# Generated by Django 3.0.7 on 2020-09-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='praxis',
            options={'verbose_name_plural': 'praxes'},
        ),
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(default='workshop_headers/default.jpg', upload_to='workshop_headers/'),
        ),
    ]
