# Generated by Django 3.0.7 on 2021-02-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontmatter',
            old_name='cheatsheets',
            new_name='cheat_sheets',
        ),
    ]
