# Generated by Django 3.1.4 on 2021-01-30 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blurb',
            unique_together={('workshop', 'text', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='discussionquestion',
            unique_together={('praxis', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='ethicalconsideration',
            unique_together={('frontmatter', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='learningobjective',
            unique_together={('frontmatter', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='nextstep',
            unique_together={('praxis', 'label')},
        ),
    ]
