# Generated by Django 3.0.7 on 2020-08-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboration',
            options={'ordering': ('current',)},
        ),
    ]
