# Generated by Django 3.0.7 on 2020-09-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20200915_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='praxis',
            name='intro',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
