# Generated by Django 3.0.7 on 2020-09-02 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='workshop.Contributor'),
        ),
    ]
