# Generated by Django 3.0.7 on 2020-09-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_praxis_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praxis',
            old_name='more_projects',
            new_name='further_projects',
        ),
    ]
