# Generated by Django 3.0.7 on 2020-10-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20200915_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontmatter',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
