# Generated by Django 3.1.4 on 2021-01-11 22:20

import backend.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glossary', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            bases=(backend.mixins.CurlyQuotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(backend.mixins.CurlyQuotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson.challenge')),
            ],
            bases=(backend.mixins.CurlyQuotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('is_required', models.BooleanField(default=False)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lesson.evaluation')),
            ],
            bases=(backend.mixins.CurlyQuotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('terms', models.ManyToManyField(blank=True, to='glossary.Term')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='workshop.workshop')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(backend.mixins.CurlyQuotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='lesson.lesson'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lesson.question')),
            ],
            bases=(backend.mixins.CurlyQuotesMixin, models.Model),
        ),
    ]
