# Generated by Django 3.0.7 on 2020-08-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_auto_20200806_1809'),
        ('lesson', '0002_lesson_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='terms',
            field=models.ManyToManyField(blank=True, to='glossary.Term'),
        ),
    ]
