# Generated by Django 3.0.7 on 2020-09-02 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_answer_evaluation_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='lesson.Lesson'),
        ),
    ]
