# Generated by Django 3.0.7 on 2021-02-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20210209_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonimage',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lesson.Lesson'),
        ),
    ]
