# Generated by Django 3.0.7 on 2020-08-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_contributor_ethicalconsideration_frontmatter_learningobjective_praxis'),
        ('lesson', '0003_auto_20200826_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='workshop.Workshop'),
        ),
    ]
