# Generated by Django 3.0.7 on 2021-02-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_auto_20210209_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonimage',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
