# Generated by Django 3.0.7 on 2020-08-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pictures')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('instructor_requested', models.BooleanField(default=False)),
            ],
        ),
    ]
