# Generated by Django 3.0.7 on 2020-08-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='workshop.Workshop'),
        ),
    ]
