# Generated by Django 3.0.7 on 2020-08-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20200831_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
