# Generated by Django 3.0.7 on 2020-09-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20200910_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
