# Generated by Django 3.0.7 on 2020-08-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instructor_requested',
            field=models.BooleanField(default=False),
        ),
    ]
