# Generated by Django 3.0.7 on 2021-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20210202_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='cat',
            field=models.CharField(choices=[('PE', 'Personal'), ('PR', 'Project')], default='PR', max_length=2),
        ),
    ]
