# Generated by Django 3.0.7 on 2020-09-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=70)),
                ('url', models.URLField()),
                ('cat', models.CharField(choices=[('PE', 'Personal'), ('PR', 'Project')], default='PR', max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.Profile')),
            ],
        ),
    ]
