# Generated by Django 3.0.7 on 2020-08-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
        ('learner', '0003_profile_instructor_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='workshop.Workshop'),
        ),
    ]
