# Generated by Django 3.0.7 on 2020-09-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0004_profilelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='cat',
            field=models.CharField(choices=[('PE', 'Personal'), ('PR', 'Projects')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='profilelink',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='learner.Profile'),
        ),
    ]
