# Generated by Django 3.0.8 on 2020-07-14 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmatter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontmatter',
            name='ethical_considerations',
        ),
        migrations.CreateModel(
            name='EthicalConsideration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=500)),
                ('frontmatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethical_considerations', to='frontmatter.Frontmatter')),
            ],
        ),
    ]
