# Generated by Django 3.0.7 on 2021-02-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='image',
            field=models.ImageField(default='insight_headers/default.png', upload_to='insight_headers/'),
        ),
    ]
