# Generated by Django 3.0.7 on 2020-09-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_auto_20200902_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='insight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='insight.Insight'),
        ),
    ]
