# Generated by Django 3.0.7 on 2020-09-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_auto_20200902_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystemspecificsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_specific_sections', to='insight.Section'),
        ),
    ]
