# Generated by Django 3.0.7 on 2020-07-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('praxis', '0002_auto_20200707_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praxis',
            name='further_readings',
            field=models.ManyToManyField(related_name='praxes', to='library.Reading'),
        ),
        migrations.AlterField(
            model_name='praxis',
            name='more_projects',
            field=models.ManyToManyField(related_name='praxes', to='library.Project'),
        ),
        migrations.AlterField(
            model_name='praxis',
            name='more_resources',
            field=models.ManyToManyField(related_name='praxes', to='library.Resource'),
        ),
        migrations.AlterField(
            model_name='praxis',
            name='tutorials',
            field=models.ManyToManyField(related_name='praxes', to='library.Tutorial'),
        ),
    ]
